### ISSUE TITLE
Reflux store is not initialized

### ISSUE THREAD

**Issue by tebeco** [fuse-box/fuse-box-ts-react-reflux-seed#10]
I could not find a way to fix that one :s

I've removed Reflux from the seed locally to make it work but i could not understand how the store should be initialized (see console error in Chrome)

**Comment by nchanged** [comment]
and why did you remove it?

**Comment by tebeco** [comment]
because, i'm trying to make it work before fixing it :)

```
fusebox-websocket@0.0.0:32 connect ws://localhost:5678
fusebox-hot-reload@0.0.0:20 connecting...
vendor.js:21537 Uncaught Error: Reflux.Store.state is inaccessible before the store has been initialized.
    at Function.get [as state] (vendor.js:21537)
    at object-assign-polyfill@0.0.0:31
    at TestStore.ts:5
    at Number.<anonymous> (TestStore.ts:18)
    at g (vendor.js:23048)
    at w.require (vendor.js:23048)
    at Number.<anonymous> (HelloWorld.tsx:4)
    at g (vendor.js:23048)
    at w.require (vendor.js:23048)
    at Number.<anonymous> (application.tsx:3)
```

**Comment by tebeco** [comment]
@nchanged
Does it works on your side ?
* Re clone the repo 
* Or rimraf node_modules dist build
`npm i` 
`npm start`
Navigate to http://localhost:3000
Open devtools on the browser and check the console

This is why I temporary removed it

**Comment by tebeco** [comment]
I've managed to make it work 
* only with react
* reflux is not friendly at all with typescript for example there's no @types for Reflux.Component class
* they don't plan to move along with typescript based on the issue I found on their GitHub 
* tried to create a real typescript class named ˋRefluxComponent` to fake the Reflux.Component I got no more error but it seems it broke the store import or something like that

So either Reflux is removed from the repo either it's fixed but I don't have the knowledge to fix it

**Comment by nchanged** [comment]
So you are saying that the repo stopped working?

**Comment by tebeco** [comment]
I've discovered the repo yesterday and I've never seen it working (stuck on that Reflux console error)

**Comment by nchanged** [comment]
do you think they have updated a version there? Maybe we should drop it?

**Comment by tebeco** [comment]
nop, beeing up to date is good but the source should be fixed

**Comment by nchanged** [comment]
I will check it out soon, thanks!

**Comment by tebeco** [comment]
I got Reflux working here :
https://github.com/tebeco/fuse-box-ts-react-reflux-seed

But it need to be udpated to Typescript, for now it's JS

**Comment by nchanged** [comment]
Ok, i updated fusebox and typescript. All working now!

**Comment by tebeco** [comment]
I don't see a commit for that

**Comment by nchanged** [comment]
It's there

**Comment by tebeco** [comment]
Can you link me the commit your talking about ?

**Comment by nchanged** [comment]
Its the latest commit on the list on commits, versions bump it's called

**Comment by tebeco** [comment]
i'm sorry but there's still an error in the console and no component are display
I've :
```
> rimraf .fusebox
> git clean -fdx
> git pull --rebase

change version for :
    "@types/node": "^7.0.7",
    "@types/react": "^15.0.14",
    "uglify-js": "^2.7.5"
    "reflux": "^6.1.0"
to 
    "@types/node": "^7.0.8",
    "@types/react": "^15.0.15",
    "uglify-js": "^2.8.11"
    "reflux": "^6.4.1"
then

> npm install
> npm start
```
I don't get how you have something working since this is the result :

![image](https://cloud.githubusercontent.com/assets/2266487/23800741/ca19de4c-05ad-11e7-95cc-496a64d0afa2.png)

**Comment by nchanged** [comment]
Right, well i did not change reflux version. Let's see..

**Comment by tebeco** [comment]
I can create a PR with a working version but it use "ES6 class" => React.CreateClass instead of the Typescript versions

please see the fork here :
https://github.com/tebeco/fuse-box-ts-react-reflux-seed

i don't want to merge this code :s
I think it's possible to use typescript classes instead of this workaround
