### ISSUE TITLE
VsCode debugger does not 'work'

### ISSUE THREAD

**Issue by tebeco** [fuse-box/fuse-box-ts-react-reflux-seed#14]
I'm still trying to make the VsCode debugger works with fusebox
i had no issue at all with Zebpackm it's as simple as this in the launch.son

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/src",
            "userDataDir": "${workspaceRoot}/.chrome",
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*"
            }
        }
    ]
}
```

but as you can see the important part is the `sourceMapOverrides`
the webpack dev server create a scehme `webpack:///` and i can't find the equivqlent for this project

also it's like production build is applied here
i would have expect to find :

`npm start` : run a dev env for debug / hmr / reload ....
`npm build` : create bundle for production deployment on a CDN or a webserver
`np; run dev` seems broken

here `npm start` mix both process and don't seem to allow web devlopment

**Comment by nchanged** [comment]
@tebeco 1.4.1 will solve many things.

https://github.com/fuse-box/fuse-box/issues/416
Try it out
