### ISSUE TITLE
Production app.js bundle also contains vendor dependencies

### ISSUE THREAD

**Issue by guillaume86** [fuse-box/fuse-box-ts-react-reflux-seed#15]
I used `gulp dist` to generate the production bundles and I noticed the app.js file is bigger than the  vendor.js file.

**Comment by nchanged** [comment]
This repo will updated to 2.0 very soon, thanks

**Comment by guillaume86** [comment]
Thanks, very cool project btw. I currently use JSPM in a big typescript project and this looks like an ideal replacement (I was looking for better load times in the dev workflow and getting rid of the jspm folder). I just need to check the few requirements I have are working first :).

**Comment by nchanged** [comment]
Cool, thanks, check the upcoming release fuse-box.org:3333 all new and shiny :)

**Comment by nchanged** [comment]
Updated!
