### ISSUE TITLE
Getting rid of Gulp ?

### ISSUE THREAD

**Issue by tebeco** [fuse-box/fuse-box-ts-react-reflux-seed#9]
The more i see to more gulp obfuscate configuration, build, etc ...

In direct comparaison to Webpack2
It turns "configuration key" to "magic stuff happens somewhere"

Is there a way in fusebox to avoid using gulp ?
and have simple npm command :
npm start / npm test / npm run build

As a one liner ? I mean, we just saw gulp reappearing, and not it's gonna be hard to convince that maybe we'll try Fuse-Box because we try to go as far as possible of gulp.

Did i missed another really simple way ?

**Comment by nchanged** [comment]
Absolutely! Could you suggest a fix?

**Comment by tebeco** [comment]
No i can't, that's my question :)
I'm actually wondering if it's possible ^^ and i'm quite sure my lowlevel of Js development is not helping

**Comment by nchanged** [comment]
Of course it is possible! =)

**Comment by tebeco** [comment]
@nchanged 

If i find a way, i'll try :)
BTW we should probably add "gulp" as a dependency (we tend to avoid install gulp globally) (it's not a CLI)

**Comment by mattoni** [comment]
Yeah, I think gulp needs to go, and be removed from the examples. Is there another way, other than creating a `fusebox.js` file and doing all the gulp stuff manually?

**Comment by nchanged** [comment]
Done
